In [1]:
# Numpy
# Numerical Python
# 고성능 수치 계산을 위한 라이브러리
# 벡터나 행렬 연산에 편리한 기능 제공
# 모든 원소는 같은 자료형만 가능

In [2]:
import numpy as np
a = np.arange( 15 ) # 1차원 데이터
print( a )
a = a.reshape( 3,5, order='F') #c행부터 할당 기본값F열부터 할당# reshape : 차원을 바꾸는 함수
#a = np.arange(15).reshape(3,5) 이것도 가능
print( a )
print( type( a )  )
print( a.shape )
print( a.dtype )
print(a.ndim) # 몇 차원 데이터인지 알려주는 것
print(a.size)
# print( dir(np)) # 넘파이에서 쓸 수 있는 것들

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2
15


In [3]:
print(a)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [4]:
b = [-1, 2, 5, -3, 0, 7, -9, 7, -4,-7] # list
print(type(b))
b = np.array(b)
print(type(b))

t = (10,20,30,40,50) # Tuple
print(type(t))
t = np.array(t)
print(type(t))

s = {10,20,30,40,50} # set
print(type(s))
s = np.array(s)
print(type(s))

# 딕셔너리는 넘파이로 바로 바꿀 수 없음. but 판다스로 호환 가능


<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'set'>
<class 'numpy.ndarray'>


In [33]:
print(b.shape)
print(b.ndim)
print(b.dtype)
print(b)

# print(help(np.arange))  # help(원하는 함수의 설명만도 볼 수 잇음) = dir 이라고 생각하면 편함
print(np.abs(b))          # 절대값
print(np.sqrt(np.abs(b))) #제곱근 / 이중함수 가능 
# nan = not a number (음수의 경우에 주로 나옴)
print(np.square(b))       # 제곱
print(np.isnan(b))        # nan이면 True 아니면 False
print(np.sum(b))          # 합계
print(np.mean(b))         # 평균
print(np.max(b))          # 최값
print(np.min(b))          # 최솟값
print(np.argmax(b))       # 최댓값 인덱스
print(np.argmin(b))       # 최솟값 인덱스
print(np.sort(b))         # 오름차순 정렬
print(np.sort(b)[::-1])   # 내림차순 정렬 [start : end : step]
print(np.median(b))       # 중간값


(10,)
1
int32
[-1  2  5 -3  0  7 -9  7 -4 -7]
[1 2 5 3 0 7 9 7 4 7]
[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.64575131 2.         2.64575131]
[ 1  4 25  9  0 49 81 49 16 49]
[False False False False False False False False False False]
-3
-0.3
7
-9
5
6
[-9 -7 -4 -3 -1  0  2  5  7  7]
[ 7  7  5  2  0 -1 -3 -4 -7 -9]
-0.5


In [35]:
c = np.zeros((3,3))

In [37]:
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
d = np.ones((3,3))

In [41]:
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
np.zeros_like(d)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones_like(c)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.random.rand(3,3)

array([[0.16612461, 0.80021697, 0.34248235],
       [0.52638382, 0.45516736, 0.31130184],
       [0.04144539, 0.54183597, 0.1425743 ]])

In [59]:
np.random.randint(1,40,size =(3,3,3)) # size =는 없어도 됨

array([[[ 3,  4, 21],
        [19, 13,  2],
        [20, 27, 25]],

       [[14,  8, 20],
        [37,  7, 25],
        [ 6, 10, 26]],

       [[18, 14,  1],
        [21, 38, 26],
        [39, 10, 24]]])

In [61]:
c+d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])